version: '3.8'

services:
  database:
    container_name: "postgresql"
    image: "postgres:16.1"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
    volumes:
      - .\data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge